### ISSUE TITLE
"ORA-22902: CURSOR expression not allowed" in Application Express 18.1.0.00.45

### ISSUE THREAD

**Issue by paulius1994zukas** [RonnyWeiss/APEX-D3-Dashboard-Charts#1]
I've successfully imported the plugin and can get the randomly generated charts in the region. However, after changing anything in the SQL query be that as simple as adding a white space to the end of the file generates "**ORA-22902: CURSOR expression not allowed**" error.

**Comment by RonnyWeiss** [comment]
Hello

What is your db version a can you send me the sql source or other further information? Thank you!

Kr

Ronny

**Comment by RonnyWeiss** [comment]
no longer relevant or incorrect
