### ISSUE TITLE
New Feature Request - ordering data set

### ISSUE THREAD

**Issue by d-s-little** [RonnyWeiss/APEX-D3-Dashboard-Charts#2]
In a bar graph, would like to be able to order the graph by the either the y or x value in ascending or descending order

**Comment by RonnyWeiss** [comment]
Hello thank you for request. Will check when implementing it.

**Comment by RonnyWeiss** [comment]
Why do you not order it by sql?

**Comment by d-s-little** [comment]
I was struggling getting the sorting to work properly with the way I was writing the query.  However,  I changed my approach and it is working perfectly now.
Thanks
    On Thursday, February 4, 2021, 05:01:45 PM CST, Ronny Weiss <notifications@github.com> wrote:  
 
 


Why do you not order it by sql?

**Comment by RonnyWeiss** [comment]
So I will close this issue because I think ordering in query should work fine. Becaus of working with JSON_ARRAYAGG you need to add sort order in there.

Have a nice weekend and have fun with the plugin.

Kind regards

Ronny
